import { Select } from '@base-ui/react/select'
import { Button } from '@base-ui/react/button'
import { CaretDown, Check, Copy, Printer } from '@phosphor-icons/react'
import type { CalcResult, VolumeUnit, WeightUnit } from '../hooks/useVanillaCalc'
import { VOLUME_UNITS, WEIGHT_UNITS, type Formula, type Fold, FORMULAS, FOLDS } from '../hooks/useVanillaCalc'

interface ResultsPanelProps {
  result: CalcResult
  formula: Formula
  fold: Fold
  volumeDisplayUnit: VolumeUnit
  setVolumeDisplayUnit: (u: VolumeUnit) => void
  weightDisplayUnit: WeightUnit
  setWeightDisplayUnit: (u: WeightUnit) => void
}

const KeyValPair = ({ k, v }: { k: string; v: string }) => (
  <div className="grid grid-cols-3 gap-1">
    <div className="text-sm text-zinc-600 dark:text-zinc-400">{k}</div>
    <div className="text-sm font-semibold text-vanilla-700 dark:text-vanilla-400 col-span-2">{v}</div>
  </div>
)


const selectTriggerCls = `
  flex items-center gap-1 rounded-lg border border-zinc-300 dark:border-zinc-700
  bg-white dark:bg-zinc-950 hover:bg-zinc-100 dark:hover:bg-white/5 text-zinc-900 dark:text-zinc-100
  px-2 py-2 text-sm cursor-pointer whitespace-nowrap
  hover:border-zinc-400 dark:hover:border-zinc-600
  focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-vanilla-400
  transition-colors
`

const selectPopupCls = `
  z-50 min-w-[110px] rounded-xl border border-zinc-200 dark:border-zinc-700
  bg-white dark:bg-zinc-900 shadow-lg py-1
  data-[starting-style]:opacity-0 data-[ending-style]:opacity-0
  transition-opacity duration-150
`

const selectItemCls = `
  flex items-center gap-2 px-3 py-1.5 text-xs cursor-pointer
  text-zinc-700 dark:text-zinc-300
  data-[highlighted]:bg-vanilla-50 dark:data-[highlighted]:bg-vanilla-950/30
  data-[highlighted]:text-vanilla-700 dark:data-[highlighted]:text-vanilla-400
`


export function ResultsPanel({
  result,
  formula,
  fold,
  volumeDisplayUnit,
  setVolumeDisplayUnit,
  weightDisplayUnit,
  setWeightDisplayUnit,
}: ResultsPanelProps) {
  const volLabel = VOLUME_UNITS[volumeDisplayUnit].label
  const wtLabel = WEIGHT_UNITS[weightDisplayUnit].label
  const foldLabel = FOLDS.find(f => f.value === fold)?.label ?? ''

  function generateRecipeText() {
    return [
      `🌿 Vanilla Extract Recipe`,
      `Formula: ${FORMULAS[formula].label} — ${foldLabel}`,
      ``,
      `1. Weigh out ${result.beansDisplay} ${wtLabel} of vanilla beans.`,
      `2. Split and scrape beans, place in a clean ${result.containerDisplay} ${volLabel} jar.`,
      `3. Pour ${result.alcoholDisplay} ${volLabel} of alcohol (80 proof / 40% ABV vodka recommended) over beans.`,
      `   Note: beans displace ~${result.displacementMl.toFixed(1)} ml, so your jar fills to ${result.containerDisplay} ${volLabel}.`,
      `4. Seal tightly, shake well, and store in a cool dark place.`,
      `5. Shake every few days. Ready in 8–12 weeks for single fold, longer for higher folds.`,
      ``,
      `Generated by Vanilla Extract Calculator`,
    ].join('\n')
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(generateRecipeText())
    } catch {
      // fallback: do nothing silently
    }
  }

  function handlePrint() {
    const win = window.open('', '_blank')
    if (!win) return
    win.document.write(`
      <html><head><title>Vanilla Extract Recipe</title>
      <style>
        body { font-family: Georgia, serif; max-width: 600px; margin: 40px auto; color: #333; }
        h1 { color: #92400e; }
        pre { white-space: pre-wrap; line-height: 1.8; font-size: 1rem; }
      </style>
      </head><body>
      <pre>${generateRecipeText()}</pre>
      </body></html>
    `)
    win.document.close()
    win.print()
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center gap-2 text-zinc-700 dark:text-zinc-300">
          <Check size={20} weight="bold"/>  
          <h2 className="text-lg font-bold">Results</h2>
        </div>
        <div className="flex gap-2">
          {/* Volume display unit selector */}
          <Select.Root value={volumeDisplayUnit} onValueChange={(v) => v && setVolumeDisplayUnit(v as VolumeUnit)}>
            <Select.Trigger className={selectTriggerCls}>
              <Select.Value />
              <Select.Icon className="text-zinc-400"><CaretDown size={12} weight="bold" /></Select.Icon>
            </Select.Trigger>
            <Select.Portal>
              <Select.Positioner sideOffset={4} align="end">
                <Select.Popup className={selectPopupCls}>
                  {(Object.entries(VOLUME_UNITS) as [VolumeUnit, { label: string }][]).map(([key, u]) => (
                    <Select.Item key={key} value={key} className={selectItemCls}>
                      <Select.ItemIndicator className="text-vanilla-600 dark:text-vanilla-400"><Check size={12} weight="bold" /></Select.ItemIndicator>
                      <Select.ItemText>{u.label}</Select.ItemText>
                    </Select.Item>
                  ))}
                </Select.Popup>
              </Select.Positioner>
            </Select.Portal>
          </Select.Root>

          {/* Weight display unit selector */}
          <Select.Root value={weightDisplayUnit} onValueChange={(v) => v && setWeightDisplayUnit(v as WeightUnit)}>
            <Select.Trigger className={selectTriggerCls}>
              <Select.Value />
              <Select.Icon className="text-zinc-400"><CaretDown size={12} weight="bold" /></Select.Icon>
            </Select.Trigger>
            <Select.Portal>
              <Select.Positioner sideOffset={4} align="end">
                <Select.Popup className={selectPopupCls}>
                  {(Object.entries(WEIGHT_UNITS) as [WeightUnit, { label: string }][]).map(([key, u]) => (
                    <Select.Item key={key} value={key} className={selectItemCls}>
                      <Select.ItemIndicator className="text-vanilla-600 dark:text-vanilla-400"><Check size={12} weight="bold" /></Select.ItemIndicator>
                      <Select.ItemText>{u.label}</Select.ItemText>
                    </Select.Item>
                  ))}
                </Select.Popup>
              </Select.Positioner>
            </Select.Portal>
          </Select.Root>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-2">
        <div className="rounded-lg border border-vanilla-500/20 bg-vanilla-500/10 p-3 flex flex-col gap-2">
          <h4 className="text-lg font-bold text-vanilla-700 dark:text-vanilla-300">Extract Formulation</h4>
          <KeyValPair k="Formula" v={FORMULAS[formula].label} />
          <KeyValPair k="Fold Strength" v={foldLabel} />
          <KeyValPair k="Container Size" v={`${result.containerDisplay} ${volLabel}`} />
          <KeyValPair k="Vanilla Beans" v={`${result.beansDisplay} ${wtLabel}`} />
          <KeyValPair k="Alcohol" v={`${result.alcoholDisplay} ${volLabel}`} />
        </div>
      </div>

      <div className="rounded-lg border border-blue-500/20 bg-blue-500/10 dark:bg-blue-500/10 p-2 space-y-1">
        <p className="text-sm font-bold text-blue-800 dark:text-blue-400">Displacement Note</p>
        <p className="text-sm text-blue-700 dark:text-blue-300">
          Beans displace <strong>{result.displacementMl.toFixed(1)} ml</strong> of liquid.
          Add <strong>{result.alcoholDisplay} {volLabel}</strong> of alcohol to a jar, then add
          <strong> {result.beansDisplay} {wtLabel}</strong> of beans — total jar fill will be
          <strong> {result.containerDisplay} {volLabel}</strong>.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-2 pt-1">
        <Button
          onClick={handleCopy}
          className="
            transition flex items-center justify-center w-full py-2 px-3.5 gap-1 m-0 outline-0 border border-zinc-200 dark:border-zinc-600 rounded-lg bg-zinc-50 dark:bg-zinc-900 font-bold text-sm text-zinc-900 dark:text-white select-none hover:data-[disabled]:bg-zinc-50 hover:bg-zinc-100 dark:hover:bg-zinc-800 active:data-[disabled]:bg-zinc-50 active:bg-zinc-200 active:shadow-[inset_0_1px_3px_rgba(0,0,0,0.1)] active:border-t-zinc-300 active:data-[disabled]:shadow-none active:data-[disabled]:border-t-zinc-200 focus-visible:outline-2 focus-visible:outline-vanilla-800 focus-visible:-outline-offset-1 data-[disabled]:text-zinc-500
          "
        >
          <Copy size={16} weight="regular" />
          Copy Recipe
        </Button>
        <Button
          onClick={handlePrint}
          className="
            transition flex items-center justify-center w-full py-2 px-3.5 gap-1 m-0 outline-0 border border-zinc-200 dark:border-zinc-600 rounded-lg bg-zinc-50 dark:bg-zinc-900 font-bold text-sm text-zinc-900 dark:text-white select-none hover:data-[disabled]:bg-zinc-50 hover:bg-zinc-100 dark:hover:bg-zinc-800 active:data-[disabled]:bg-zinc-50 active:bg-zinc-200 active:shadow-[inset_0_1px_3px_rgba(0,0,0,0.1)] active:border-t-zinc-300 active:data-[disabled]:shadow-none active:data-[disabled]:border-t-zinc-200 focus-visible:outline-2 focus-visible:outline-vanilla-800 focus-visible:-outline-offset-1 data-[disabled]:text-zinc-500
          "
        >
          <Printer size={16} weight="regular" />
          Print Recipe
        </Button>
      </div>
    </div>
  )
}
